sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t wongni/docker-react .

script:
  - docker run -e CI=true wongni/docker-react npm run test
